---
galaxy_info:
  author: power-playbooks
  description: Register one LPAR for PXE (MAC from HMC, TFTP, kickstart, ISC/KEA DHCP)
  license: GPL-3.0-or-later
  min_ansible_version: ">=2.14.0"
  galaxy_tags:
    - ibm
    - power
    - pxe
    - kickstart
    - dhcp
    - kea

dependencies: []
