---
galaxy_info:
  author: power-playbooks
  description: Create a logical volume on VIOS and map it to an LPAR via virtual SCSI
  license: GPL-3.0-or-later
  min_ansible_version: ">=2.14.0"
  galaxy_tags:
    - ibm
    - power
    - hmc
    - vios
    - lpar
    - storage

# Requires: Ansible collection ibm.power_hmc (see repository requirements.yml)
